name: .NET Build
on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Install dependencies
      run: msbuild -t:restore
    - name: Build project
      run: msbuild "NASB Voice Mod/NASB Voice Mod.csproj" /t:Build /p:Configuration=Release
    - name: Prepare release files
      shell: bash
      run: |
        find "NASB Voice Mod/bin/Release/netstandard2.0" -type f ! -name "VoiceMod.dll" -delete
        cp "LICENSE" "NASB Voice Mod/bin/Release/netstandard2.0/LICENSE.VoiceMod.txt"
        cp -a "NASB Voice Mod/Resources/." "NASB Voice Mod/bin/Release/netstandard2.0/"
    # - name: Upload Build
    #   if: startsWith(github.ref, 'refs/tags/') == false
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: ModAssistant-${{ github.sha }}
    #     path: ./ModAssistant/bin/Release/
    # - name: Extract Release Version
    #   if: startsWith(github.ref, 'refs/tags/')
    #   id: get_version
    #   shell: bash
    #   run: echo ::set-output name=version::${GITHUB_REF#refs/tags/v}
    # - name: Release
    #   if: startsWith(github.ref, 'refs/tags/')
    #   uses: softprops/action-gh-release@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     name: Mod Assistant v${{ steps.get_version.outputs.version }}
    #     files: ./ModAssistant/bin/Release/ModAssistant.exe